name = "rustybooks"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"
services = [
    { binding = "auth", service = "firebase-verifier" }
]

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]

# necessary secrets:

# OPENAI_KEY
# VERIFIER_URI
